add visualize_results_v2 in launch.py
facebookresearch/DetectAndTrack pull request #58
Opened 2018-11-15 11:34 UTC by SeanSyue

add visualize_results_v2 in launch.py

2018-11-15 15:36 UTC, rohitgirdhar commented on launch.py
> +    tool_file = 'visualize_results_v2.py'
An indentation seems missing here..

2018-11-15 15:37 UTC, rohitgirdhar requested changes
Thanks! Please fix the indent

2018-11-16 02:58 UTC, SeanSyue commented
@rohitgirdhar Ok, I've fixxed it.

2018-11-16 03:30 UTC, SeanSyue commented
@rohitgirdhar Thx, I've fixxed it.

2018-11-20 06:44 UTC, rohitgirdhar approved these changes

2018-11-20 06:44 UTC, merged